spring:
  datasource:
    username: ${db_user}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
jwt:
  secret: ${jwt_secret}
