spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/budget_app
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
