spring:
  liquibase:
    enabled: true
    change-log: classpath:/dblogs/changelog/db.changelog-master.yaml
  datasource:
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    password: ${DB_PASSWORD}

  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
jwt:
  secret: ${JWT_SECRET}
server:
  port: 8081

